# create some sample grapes
Grape.create(name: 'Carmenere')
Grape.create(name: 'Cabernet Sauvignon')
Grape.create(name: 'Malbec')
Grape.create(name: 'Zweigelt')
Grape.create(name: 'Gewürztraminer')
Grape.create(name: 'Merlot')
Grape.create(name: 'Syrah')
Grape.create(name: 'Sauvignon blanc')
Grape.create(name: 'Chardonnay')
