# create some sample grapes
Grape.create('Carmenere')
Grape.create('Cabernet Sauvignon')
Grape.create('Malbec')
Grape.create('Zweigelt')
Grape.create('Gewürztraminer')
Grape.create('Merlot')
Grape.create('Syrah')
Grape.create('Sauvignon blanc')
Grape.create('Chardonnay')
